Repository Teika7778/DMiTI, pull requests merged in 2024-11, with the labels that each got.

#38 DIV_PP_P
  core/DIV_PP_P.py
  core/tests/DIV_PP_P_test.py
Labels: Заглушки

#26 SUB_PP_P
  core/SUB_PP_P.py
  core/tests/SUB_PP_P_test.py
Labels: Заглушки, SUB_QQ_Q

#49 MUL_PP_P
  core/MUL_PP_P.py
  core/tests/MUL_PP_P_test.py
Labels: Заглушки, ADD_PP_P

#36 MOD_PP_P
  core/MOD_PP_P.py
  core/tests/MOD_PP_P_test.py
Labels: Заглушки, MUL_PP_P

#48 GCF_PP_P
  core/GCF_PP_P.py
  core/tests/GCF_PP_P_test.py
Labels: Заглушки, MOD_PP_P

#37 NMR_P_P
  core/NMR_P_P.py
  core/tests/NMR_P_P_test.py
Labels: Заглушки, GCF_PP_P
